- id: pysentry
  name: pysentry (DEPRECATED - moved to pysentry/pysentry-pre-commit)
  description: "⚠️ DEPRECATED - See github.com/pysentry/pysentry-pre-commit"
  entry: pysentry-rs
  language: python
  always_run: true
  additional_dependencies:
    ["pysentry-rs==0.3.5", "uv==0.8.9", "pip-tools==7.5.0"]
  minimum_pre_commit_version: "2.9.2"
  types: [python]
